replicaCount: 1

image:
  repository: docker.io/mayday24/bnl-application
  tag: 1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  DYNAMIC_STRING: "Setupped from helm chart"
